import linear_operators_belonging_operator_ideals_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace linear_operators_belonging_operator_ideals_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end linear_operators_belonging_operator_ideals_lemma_canonical_lane_mathlib
end HautevilleHouse
